clear
clc
close all

scenario = M8_CreateScenarioInputs("CattleCrossing");

result = M8_RunScenario(scenario);

metrics = M8_CalculateMetrics(result);

figure

plot( ...
    result.egoTrajectory(:,1), ...
    result.egoTrajectory(:,2), ...
    "LineWidth",2)

hold on

plot( ...
    result.objectTrajectory(:,1), ...
    result.objectTrajectory(:,2), ...
    "--", ...
    "LineWidth",2)

plot( ...
    scenario.goalPoint(1), ...
    scenario.goalPoint(2), ...
    "x", ...
    "MarkerSize",10, ...
    "LineWidth",2)

plot( ...
    scenario.obstacleStart(1), ...
    scenario.obstacleStart(2), ...
    "o", ...
    "MarkerSize",8, ...
    "LineWidth",2)

plot( ...
    result.egoTrajectory( ...
    round(scenario.avoidanceStart / scenario.dt) + 1,1), ...
    result.egoTrajectory( ...
    round(scenario.avoidanceStart / scenario.dt) + 1,2), ...
    "d", ...
    "MarkerSize",9, ...
    "LineWidth",2)

plot( ...
    result.objectTrajectory( ...
    find(result.time == result.minimumClearanceTime,1),1), ...
    result.objectTrajectory( ...
    find(result.time == result.minimumClearanceTime,1),2), ...
    "s", ...
    "MarkerSize",9, ...
    "LineWidth",2)

legend( ...
    "Ego Trajectory", ...
    "Moving Cattle", ...
    "Goal", ...
    "Cattle Start", ...
    "Avoidance Trigger", ...
    "Closest Approach", ...
    "Location","best")

title("M8 Stage 1 Closed-Loop Validation Test")
xlabel("X [meters]")
ylabel("Y [meters]")
grid on
axis equal

hold off

fprintf("\nM8 STAGE 1 VALIDATION\n")
fprintf("----------------------\n")
fprintf("Scenario:                  %s\n",metrics.scenario)
fprintf("Completed:                 %d\n",metrics.completed)
fprintf("Collision free:            %d\n",metrics.collisionFree)
fprintf("Minimum clearance:         %.2f m\n",metrics.minimumClearance)
fprintf("Closest approach time:     %.2f s\n",metrics.minimumClearanceTime)
fprintf("Goal distance:              %.2f m\n",metrics.goalDistance)
fprintf("Path length:                %.2f m\n",metrics.pathLength)
fprintf("Path smoothness:            %.4f\n",metrics.pathSmoothness)
fprintf("Replanning latency:         %.4f s\n",metrics.replanningLatency)
fprintf("Replan count:               %d\n",metrics.replanCount)