clear
clc
close all

cfg = projectConfig;

map = M6_CreateMap;

startPose = [5 5 0];
goalPose = [55 25 0];

[pathInitial,infoInitial,initialPlanningTime] = ...
    M6_PlanPath(map,startPose,goalPose);

initialStates = pathInitial.States;

pedestrian.id = 1;
pedestrian.class = "pedestrian";
pedestrian.position = [24 9];
pedestrian.velocity = [0 3];
pedestrian.heading = pi/2;
pedestrian.timestamp = 0;

replanThreshold = 3.5;

[predictedTrajectory,minPredictedClearance,predictedConflictPoint,replanRequired,triggerIndex,triggerPoint] = ...
    M6_PredictConflict( ...
    initialStates, ...
    pedestrian, ...
    cfg.planning.predictionHorizon, ...
    replanThreshold);

obstacleCenter = predictedConflictPoint;
obstacleHalfSize = [2 2];

initialObstacleClearance = ...
    M6_CalculateClearance( ...
    initialStates, ...
    obstacleCenter, ...
    obstacleHalfSize);

if replanRequired

    [xo,yo] = meshgrid( ...
        obstacleCenter(1)-obstacleHalfSize(1):0.25:obstacleCenter(1)+obstacleHalfSize(1), ...
        obstacleCenter(2)-obstacleHalfSize(2):0.25:obstacleCenter(2)+obstacleHalfSize(2));

    setOccupancy(map,[xo(:) yo(:)],1);

    safeTriggerIndex = max(1,triggerIndex - 12);

    while safeTriggerIndex > 1

        candidatePose = initialStates(safeTriggerIndex,:);

        occupancyValue = getOccupancy(map,candidatePose(1:2));

        if occupancyValue < 0.5
            break
        end

        safeTriggerIndex = safeTriggerIndex - 1;

    end

    replanningStartPose = initialStates(safeTriggerIndex,:);

    [pathReplanned,infoReplanned,replanningLatency,replanCount] = ...
        M6_Replan( ...
        map, ...
        replanningStartPose, ...
        goalPose, ...
        replanRequired);

    if infoReplanned.IsPathFound
        replannedStates = pathReplanned.States;
    else
        replannedStates = initialStates;
    end

    actualTriggerPoint = replanningStartPose(1:2);

else

    pathReplanned = pathInitial;
    infoReplanned = infoInitial;
    replanningLatency = 0;
    replanCount = 0;
    replannedStates = initialStates;
    actualTriggerPoint = triggerPoint(1:2);

end

metrics = M6_CalculateMetrics( ...
    initialStates, ...
    replannedStates, ...
    initialPlanningTime, ...
    replanningLatency, ...
    minPredictedClearance, ...
    replanCount, ...
    map, ...
    obstacleCenter, ...
    obstacleHalfSize);

figure

show(map)
ax = gca;
hold(ax,"on")

h1 = plot(ax, ...
    initialStates(:,1), ...
    initialStates(:,2), ...
    "--", ...
    "LineWidth",2);

h2 = plot(ax, ...
    replannedStates(:,1), ...
    replannedStates(:,2), ...
    "-", ...
    "LineWidth",2);

h3 = plot(ax, ...
    predictedTrajectory(:,1), ...
    predictedTrajectory(:,2), ...
    ":", ...
    "LineWidth",2);

h4 = plot(ax, ...
    startPose(1), ...
    startPose(2), ...
    "o", ...
    "MarkerSize",8, ...
    "LineWidth",2);

h5 = plot(ax, ...
    goalPose(1), ...
    goalPose(2), ...
    "x", ...
    "MarkerSize",10, ...
    "LineWidth",2);

h6 = plot(ax, ...
    actualTriggerPoint(1), ...
    actualTriggerPoint(2), ...
    "d", ...
    "MarkerSize",10, ...
    "LineWidth",2);

h7 = plot(ax, ...
    predictedConflictPoint(1), ...
    predictedConflictPoint(2), ...
    "s", ...
    "MarkerSize",10, ...
    "LineWidth",2);

rectangle(ax, ...
    "Position",[ ...
    obstacleCenter(1)-obstacleHalfSize(1), ...
    obstacleCenter(2)-obstacleHalfSize(2), ...
    2*obstacleHalfSize(1), ...
    2*obstacleHalfSize(2)], ...
    "LineWidth",2);

h8 = plot(ax,NaN,NaN,"s","MarkerSize",10,"LineWidth",2);

legend(ax, ...
    [h1 h2 h3 h4 h5 h6 h7 h8], ...
    { ...
    "Initial Path", ...
    "Replanned Path", ...
    "Predicted Trajectory", ...
    "Start", ...
    "Goal", ...
    "Replanning Trigger", ...
    "Predicted Conflict Point", ...
    "Dynamic Obstacle"}, ...
    "Location","northeast");

title(ax,"M6 Prediction-Aware Adaptive Hybrid A*")
xlabel(ax,"X [meters]")
ylabel(ax,"Y [meters]")

hold(ax,"off")

fprintf("\nM6 ADAPTIVE PATH PLANNING\n")
fprintf("--------------------------\n")
fprintf("Initial path found:            %d\n",infoInitial.IsPathFound)
fprintf("Replanned path found:          %d\n",infoReplanned.IsPathFound)
fprintf("Initial map collision:         %d\n",metrics.initialMapCollision)
fprintf("Replanned map collision:       %d\n",metrics.replannedMapCollision)
fprintf("Collision free after replan:   %d\n",metrics.collisionFree)
fprintf("Predicted clearance:           %.2f m\n",metrics.minimumPredictedClearance)
fprintf("Initial obstacle clearance:    %.2f m\n",initialObstacleClearance)
fprintf("Replanned obstacle clearance:  %.2f m\n",metrics.replannedObstacleClearance)
fprintf("Replan threshold:              %.2f m\n",replanThreshold)
fprintf("Replan required:               %d\n",replanRequired)
fprintf("Replan count:                  %d\n",metrics.replanCount)
fprintf("Replan trigger:                [%.2f %.2f]\n",actualTriggerPoint(1),actualTriggerPoint(2))
fprintf("Conflict point:                [%.2f %.2f]\n",predictedConflictPoint(1),predictedConflictPoint(2))
fprintf("Initial planning time:         %.4f s\n",metrics.initialPlanningTime)
fprintf("Replanning latency:            %.4f s\n",metrics.replanningLatency)
fprintf("Initial path length:            %.2f m\n",metrics.initialPathLength)
fprintf("Replanned path length:          %.2f m\n",metrics.replannedPathLength)
fprintf("Initial smoothness:             %.4f\n",metrics.initialSmoothness)
fprintf("Replanned smoothness:           %.4f\n",metrics.replannedSmoothness)