clear
clc
close all

cfg = projectConfig;

input.map = M6_CreateMap;

input.startPose = [5 5 0];
input.goalPose = [55 25 0];

input.predictedObjects(1).id = 1;
input.predictedObjects(1).class = "pedestrian";
input.predictedObjects(1).position = [24 9];
input.predictedObjects(1).velocity = [0 3];
input.predictedObjects(1).heading = pi/2;
input.predictedObjects(1).timestamp = 0;

input.decision.behavior = "AVOID";
input.decision.replanRequired = true;

output = M6_AdaptivePathPlanner(input);

figure

show(input.map)
hold on

plot( ...
    output.initialStates(:,1), ...
    output.initialStates(:,2), ...
    "--", ...
    "LineWidth",2)

plot( ...
    output.selectedStates(:,1), ...
    output.selectedStates(:,2), ...
    "-", ...
    "LineWidth",2)

plot( ...
    output.predictedTrajectory(:,1), ...
    output.predictedTrajectory(:,2), ...
    ":", ...
    "LineWidth",2)

plot( ...
    input.startPose(1), ...
    input.startPose(2), ...
    "o", ...
    "MarkerSize",8, ...
    "LineWidth",2)

plot( ...
    input.goalPose(1), ...
    input.goalPose(2), ...
    "x", ...
    "MarkerSize",10, ...
    "LineWidth",2)

plot( ...
    output.triggerPoint(1), ...
    output.triggerPoint(2), ...
    "d", ...
    "MarkerSize",10, ...
    "LineWidth",2)

plot( ...
    output.conflictPoint(1), ...
    output.conflictPoint(2), ...
    "s", ...
    "MarkerSize",10, ...
    "LineWidth",2)

legend( ...
    "Initial Path", ...
    "Selected Path", ...
    "Predicted Trajectory", ...
    "Start", ...
    "Goal", ...
    "Replanning Trigger", ...
    "Conflict Point", ...
    "Location","northeast")

title("M6 Integration Interface")
xlabel("X [meters]")
ylabel("Y [meters]")

hold off

fprintf("\nM6 INTEGRATION INTERFACE\n")
fprintf("-------------------------\n")
fprintf("Success:                      %d\n",output.success)
fprintf("Behavior:                     %s\n",output.decision.behavior)
fprintf("Replan required:              %d\n",output.replanRequired)
fprintf("Replan count:                 %d\n",output.metrics.replanCount)
fprintf("Predicted clearance:          %.2f m\n",output.predictedClearance)
fprintf("Replanned clearance:          %.2f m\n",output.metrics.replannedObstacleClearance)
fprintf("Planning time:                %.4f s\n",output.metrics.initialPlanningTime)
fprintf("Replanning latency:           %.4f s\n",output.metrics.replanningLatency)
fprintf("Selected path length:         %.2f m\n",output.metrics.replannedPathLength)
fprintf("Collision free:               %d\n",output.metrics.collisionFree)