clear
clc
close all

map = M6_CreateMap;

startPose = [5 15 0];
goalPose = [55 15 0];

input.map = map;
input.startPose = startPose;
input.goalPose = goalPose;

input.predictedObjects = struct( ...
    "position",[5 0], ...
    "velocity",[0 0]);

input.decision.replanRequired = true;
input.decision.behavior = "AVOID";

m6Output = M6_AdaptivePathPlanner(input);

if ~m6Output.success
    error("M6 adaptive path planning failed.")
end

targetStates = m6Output.selectedStates;
targetPath = targetStates(:,1:2);
targetHeading = targetStates(:,3);

dt = 0.05;
simulationTime = 0:dt:20;

vehicleStates = zeros(numel(simulationTime),4);
steeringCommands = zeros(numel(simulationTime),1);
speedCommands = zeros(numel(simulationTime),1);
crossTrackErrors = zeros(numel(simulationTime),1);

vehicleStates(1,:) = [ ...
    targetPath(1,1), ...
    targetPath(1,2), ...
    targetHeading(1), ...
    0];

previousIndex = 1;
goalReached = false;

for k = 1:numel(simulationTime)-1

    currentState = vehicleStates(k,:);

    [steeringCommand,speedCommand,targetIndex,crossTrackError] = ...
        M7_Controller( ...
        currentState, ...
        targetPath, ...
        targetHeading, ...
        previousIndex);

    nextState = M7_VehicleModel( ...
        currentState, ...
        steeringCommand, ...
        speedCommand, ...
        dt);

    vehicleStates(k+1,:) = nextState;

    steeringCommands(k) = steeringCommand;
    speedCommands(k) = speedCommand;
    crossTrackErrors(k) = crossTrackError;

    previousIndex = targetIndex;

    goalDistance = norm( ...
        nextState(1:2) - targetPath(end,:));

    if goalDistance < 0.8 && nextState(4) < 0.5

        goalReached = true;

        vehicleStates(k+1:end,:) = repmat( ...
            nextState, ...
            numel(simulationTime)-k, ...
            1);

        steeringCommands(k+1:end) = 0;
        speedCommands(k+1:end) = 0;
        crossTrackErrors(k+1:end) = 0;

        break

    end

end

if ~goalReached

    steeringCommands(end) = steeringCommands(end-1);
    speedCommands(end) = speedCommands(end-1);
    crossTrackErrors(end) = crossTrackErrors(end-1);

end

metrics = M7_CalculateMetrics( ...
    vehicleStates, ...
    steeringCommands, ...
    speedCommands, ...
    crossTrackErrors, ...
    targetPath, ...
    goalReached, ...
    map);

handoff.M7 = metrics;
handoff.M7.vehicleStates = vehicleStates;
handoff.M7.steeringCommands = steeringCommands;
handoff.M7.speedCommands = speedCommands;
handoff.M7.crossTrackErrors = crossTrackErrors;
handoff.M7.simulationTime = simulationTime;
handoff.M7.targetPath = targetPath;
handoff.M7.targetHeading = targetHeading;

handoff.M6.success = m6Output.success;
handoff.M6.replanRequired = m6Output.replanRequired;
handoff.M6.replanCount = m6Output.metrics.replanCount;
handoff.M6.predictedClearance = m6Output.predictedClearance;
handoff.M6.replannedObstacleClearance = ...
    m6Output.metrics.replannedObstacleClearance;
handoff.M6.planningTime = ...
    m6Output.metrics.initialPlanningTime;
handoff.M6.replanningLatency = ...
    m6Output.metrics.replanningLatency;

Results = table( ...
    metrics.meanTrackingError, ...
    metrics.maximumTrackingError, ...
    metrics.finalPositionError, ...
    rad2deg(metrics.maximumSteering), ...
    metrics.averageSpeed, ...
    metrics.vehiclePathLength, ...
    metrics.targetPathLength, ...
    metrics.goalReached, ...
    metrics.mapCollision, ...
    metrics.collisionFree, ...
    "VariableNames",{ ...
    "MeanTrackingError", ...
    "MaximumTrackingError", ...
    "FinalPositionError", ...
    "MaximumSteeringDeg", ...
    "AverageSpeed", ...
    "VehiclePathLength", ...
    "TargetPathLength", ...
    "GoalReached", ...
    "MapCollision", ...
    "CollisionFree"});

if ~exist("Results","dir")
    mkdir("Results")
end

if ~exist("Figures","dir")
    mkdir("Figures")
end

writetable( ...
    Results, ...
    "Results/M7_Stage4_Metrics.csv");

save( ...
    "Results/M7_Stage4_Handoff.mat", ...
    "handoff");

figure

tiledlayout(2,2)

nexttile

plot( ...
    targetPath(:,1), ...
    targetPath(:,2), ...
    "--", ...
    "LineWidth",2)

hold on

plot( ...
    vehicleStates(:,1), ...
    vehicleStates(:,2), ...
    "LineWidth",2)

plot( ...
    targetPath(1,1), ...
    targetPath(1,2), ...
    "o", ...
    "MarkerSize",8, ...
    "LineWidth",2)

plot( ...
    targetPath(end,1), ...
    targetPath(end,2), ...
    "x", ...
    "MarkerSize",10, ...
    "LineWidth",2)

legend( ...
    "M6 Target Path", ...
    "M7 Vehicle", ...
    "Start", ...
    "Goal", ...
    "Location","best")

title("M7 Final Path Tracking")
xlabel("X [meters]")
ylabel("Y [meters]")
axis equal
grid on

nexttile

plot( ...
    simulationTime, ...
    crossTrackErrors, ...
    "LineWidth",2)

title("Tracking Error")
xlabel("Time [seconds]")
ylabel("Error [meters]")
grid on

nexttile

plot( ...
    simulationTime, ...
    rad2deg(steeringCommands), ...
    "LineWidth",2)

title("Steering Command")
xlabel("Time [seconds]")
ylabel("Steering [degrees]")
grid on

nexttile

plot( ...
    simulationTime, ...
    vehicleStates(:,4), ...
    "LineWidth",2)

hold on

plot( ...
    simulationTime, ...
    speedCommands, ...
    "--", ...
    "LineWidth",2)

legend( ...
    "Actual Speed", ...
    "Commanded Speed", ...
    "Location","best")

title("Vehicle Speed")
xlabel("Time [seconds]")
ylabel("Speed [m/s]")
grid on

sgtitle("M7 Stage 4 — Metrics and M8 Handoff")

saveas( ...
    gcf, ...
    "Figures/M7_Stage4_MetricsDashboard.png");

fprintf("\nM7 STAGE 4 METRICS AND M8 HANDOFF\n")
fprintf("-------------------------------------\n")
fprintf("M6 success:                  %d\n",m6Output.success)
fprintf("M6 replanning required:      %d\n",m6Output.replanRequired)
fprintf("M6 replans:                  %d\n",m6Output.metrics.replanCount)
fprintf("M7 goal reached:             %d\n",metrics.goalReached)
fprintf("M7 map collision:             %d\n",metrics.mapCollision)
fprintf("M7 collision free:            %d\n",metrics.collisionFree)
fprintf("Mean tracking error:          %.3f m\n",metrics.meanTrackingError)
fprintf("Maximum tracking error:       %.3f m\n",metrics.maximumTrackingError)
fprintf("Final position error:         %.3f m\n",metrics.finalPositionError)
fprintf("Maximum steering:             %.2f deg\n",rad2deg(metrics.maximumSteering))
fprintf("Average speed:                %.3f m/s\n",metrics.averageSpeed)
fprintf("Vehicle path length:          %.3f m\n",metrics.vehiclePathLength)
fprintf("Target path length:           %.3f m\n",metrics.targetPathLength)
fprintf("M6 planning time:             %.4f s\n",handoff.M6.planningTime)
fprintf("M6 replanning latency:        %.4f s\n",handoff.M6.replanningLatency)
fprintf("M6 predicted clearance:       %.3f m\n",handoff.M6.predictedClearance)
fprintf("M6 final obstacle clearance:  %.3f m\n",handoff.M6.replannedObstacleClearance)
fprintf("Handoff file:                 Results/M7_Stage4_Handoff.mat\n")
fprintf("Metrics file:                 Results/M7_Stage4_Metrics.csv\n")